# Generated by Django 3.0.7 on 2020-10-22 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0010_comment_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='num_of_comments',
        ),
        migrations.RemoveField(
            model_name='post',
            name='views',
        ),
    ]
