# Generated by Django 3.0.7 on 2020-10-23 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0016_auto_20201023_0346'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img_for_editor',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
