# Generated by Django 3.0.7 on 2020-10-23 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0017_post_img_for_editor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img_for_editor',
            field=models.ImageField(default='test.png', upload_to=''),
            preserve_default=False,
        ),
    ]
