# Generated by Django 3.0.7 on 2020-10-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0018_auto_20201024_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img_for_editor',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
