# Generated by Django 3.0.7 on 2020-11-02 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0020_auto_20201026_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
