# Generated by Django 3.0.7 on 2020-11-17 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0021_post_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, to='blogapp.Comment'),
        ),
        migrations.AlterField(
            model_name='post',
            name='views',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
