# Generated by Django 3.0.7 on 2020-11-17 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0026_auto_20201117_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='reply_comments',
        ),
    ]
