# Generated by Django 3.0.7 on 2020-11-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0027_remove_comment_reply_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img_url',
            field=models.CharField(blank=True, default='none.png', max_length=255, null=True),
        ),
    ]
